(function(g){var window=this;var j6=function(a){g.dI.call(this,{I:"div",N:"ytp-miniplayer-ui"});this.player=a;this.K=!1;this.J=this.F=this.B=void 0;this.R(a,"minimized",this.PT);this.R(a,"onStateChange",this.rX)},k6=function(a){g.sU.call(this,a);
this.o=new j6(this.player);this.o.hide();g.iU(this.player,this.o.element,4);a.app.J.o&&(this.load(),g.U(a.getRootNode(),"ytp-player-minimized",!0))};
g.t(j6,g.dI);g.h=j6.prototype;
g.h.show=function(){this.B=new g.zu(this.gQ,null,this);this.B.start();if(!this.K){this.H=new g.HZ(this.player,this);g.M(this,this.H);g.iU(this.player,this.H.element,4);this.H.F=.6;this.O=new g.dZ(this.player);g.M(this,this.O);this.G=new g.V({I:"div",N:"ytp-miniplayer-scrim"});g.M(this,this.G);this.G.xa(this.element);this.R(this.G.element,"click",this.tE);var a=new g.V({I:"button",ea:["ytp-miniplayer-close-button","ytp-button"],T:{"aria-label":"Close"},P:[g.OU()]});g.M(this,a);a.xa(this.G.element);
this.R(a.element,"click",this.LC);this.D=new g.V({I:"div",N:"ytp-miniplayer-controls"});g.M(this,this.D);this.D.xa(this.G.element);this.R(this.D.element,"click",this.tE);var b=new g.V({I:"div",N:"ytp-miniplayer-button-container"});g.M(this,b);b.xa(this.D.element);a=new g.V({I:"div",N:"ytp-miniplayer-play-button-container"});g.M(this,a);a.xa(this.D.element);var c=new g.V({I:"div",N:"ytp-miniplayer-button-container"});g.M(this,c);c.xa(this.D.element);this.M=new g.cY(this.player,this,!1);g.M(this,this.M);
this.M.xa(b.element);b=new g.aY(this.player,this);g.M(this,b);b.xa(a.element);this.L=new g.cY(this.player,this,!0);g.M(this,this.L);this.L.xa(c.element);this.J=new g.RY(this.player,this);g.M(this,this.J);this.J.xa(this.G.element);this.F=new g.dY(this.player,this);g.M(this,this.F);g.iU(this.player,this.F.element,4);this.C=new g.V({I:"div",N:"ytp-miniplayer-buttons"});g.M(this,this.C);g.iU(this.player,this.C.element,4);this.C.hide();a=new g.V({I:"button",ea:["ytp-miniplayer-close-button","ytp-button"],
T:{"aria-label":"Close"},P:[g.OU()]});g.M(this,a);a.xa(this.C.element);this.R(a.element,"click",this.LC);a=new g.V({I:"button",ea:["ytp-miniplayer-replay-button","ytp-button"],T:{"aria-label":"Close"},P:[g.PU()]});g.M(this,a);a.xa(this.C.element);this.R(a.element,"click",this.UU);this.R(this.player,"presentingplayerstatechange",this.hQ);this.R(this.player,"appresize",this.kv);this.R(this.player,"fullscreentoggled",this.kv);this.kv();this.K=!0}0!=this.player.Qh()&&g.dI.prototype.show.call(this);this.F.show();
this.player.Lm("annotations_module")};
g.h.hide=function(){this.B&&(this.B.dispose(),this.B=void 0);g.dI.prototype.hide.call(this);this.player.app.J.o||(this.K&&this.F.hide(),this.player.xk("annotations_module"))};
g.h.X=function(){this.B&&(this.B.dispose(),this.B=void 0);g.dI.prototype.X.call(this)};
g.h.LC=function(){this.player.Uc();this.player.ya("onCloseMiniplayer")};
g.h.UU=function(){this.player.Tc()};
g.h.tE=function(a){if(a.target==this.G.element||a.target==this.D.element)g.X(this.player).experiments.o("kevlar_miniplayer_scrim_pause")?2==this.player.Qh()?this.player.Tc():this.player.pd():this.player.ya("onExpandMiniplayer")};
g.h.PT=function(){g.U(this.player.getRootNode(),"ytp-player-minimized",this.player.app.J.o);this.player.app.J.o&&0==this.player.Qh()?this.C.show():this.C.hide()};
g.h.gQ=function(){g.iva(this.F);this.J.C();this.B&&this.B.start()};
g.h.hQ=function(a){g.W(a.state,32)&&this.H.hide()};
g.h.kv=function(){var a=this.F,b=g.QT(this.player).Wa().width;a.Ha=0;a.F=b;a.H=!1;g.fY(a)};
g.h.rX=function(a){this.player.app.J.o&&(0==a?(this.hide(),this.C.show()):(this.show(),this.C.hide()))};
g.h.Sb=function(){return this.H};
g.h.od=function(){return!1};
g.h.jk=function(){return!1};
g.h.IF=function(){};
g.h.Jo=function(){};
g.h.Ko=function(){};
g.h.Rm=function(){return null};
g.h.hv=function(){return new g.jh(0,0,0,0)};
g.h.jv=function(){};
g.h.yq=function(a,b,c,d,e){a.style.left="";a.style.top="";a.style.bottom="";d=g.Qh(a);var f=g.QT(this.player).Wa().width;b&&["ytp-prev-button","ytp-next-button"].some(function(a){return g.Lq(b,a)})?(c=12,a.style.top=12+(e||0)+"px"):(c-=d.width/2,a.style.bottom=25+(e||0)+"px");
a.style.left=g.md(c,0,f-d.width)+"px"};
g.h.fq=function(){};
g.h.lv=function(){};g.t(k6,g.sU);k6.prototype.init=function(){};
k6.prototype.load=function(){this.player.zC();this.o.show()};
k6.prototype.unload=function(){this.player.BC();this.o.hide()};g.rX.miniplayer=k6;})(_yt_player);
